name: Build and Deploy to AWS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  AWS_PRIVATE_KEY: ${{ secrets.KEYAWS }}
  SSH_OPTIONS: '-o StrictHostKeyChecking=no -i key.pem ubuntu@98.80.44.121'

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set permissions for private key
        run: |
          echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
      
      - name: Transfer code to AWS instance
        run: |
          scp ${{ env.SSH_OPTIONS }} -r ./tupan/ ubuntu@98.80.44.121:/home/ubuntu/tupan/
      
      - name: SSH into AWS and build Docker image
        run: |
          ssh ${{ env.SSH_OPTIONS }} 'cd /home/ubuntu/tupan && sudo docker build -t iagocpv/tupan-front:latest .'
      
      - name: Stop running container
        run: |
          ssh ${{ env.SSH_OPTIONS }} 'sudo docker stop tupan-front || true'
          ssh ${{ env.SSH_OPTIONS }} 'sudo docker rm tupan-front || true'
      
      - name: Run new container
        run: |
          ssh ${{ env.SSH_OPTIONS }} 'sudo docker run -d --name tupan-front -p 80:3000 iagocpv/tupan-front:latest'
      
      - name: Cleanup SSH key
        run: |
          rm -f key.pem
