name: Lint and Unit Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --prefix tupan --legacy-peer-deps

      - name: Run linting
        run: npm run lint --prefix tupan

      - name: Run Jest tests
        run: npm test --prefix tupan
