name: Auto Generate PR Title and Description

on:
  pull_request:
    types: [opened, edited]

jobs:
  generate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get current branch name
        id: get_branch
        run: echo "branch_name=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Get all commit messages
        id: get_commits
        run: |
          CURRENT_BRANCH="${{ env.branch_name }}"
          COMMITS=$(git log --pretty=format:"%s" "${CURRENT_BRANCH}^..${CURRENT_BRANCH}")
          echo "commits=$COMMITS" >> $GITHUB_ENV

      - name: Analyze commits and generate PR title/description
        id: generate_pr_title
        run: |
          COMMITS="${{ env.commits }}"
          BRANCH_NAME="${{ env.branch_name }}"

          # Extract branch details
          TASK_ID=$(echo "$BRANCH_NAME" | cut -d'-' -f1)
          TAG_TIPO=$(echo "$BRANCH_NAME" | cut -d'-' -f2 | cut -d'/' -f1)
          DESCRICAO_BRANCH=$(echo "$BRANCH_NAME" | cut -d'/' -f2)

          # Analyze commits for tags
          if echo "$COMMITS" | grep -q '^func'; then
              TITLE="Funcionalidade: $DESCRICAO_BRANCH - Task #$TASK_ID"
          elif echo "$COMMITS" | grep -q '^corr'; then
              TITLE="Correção: $DESCRICAO_BRANCH - Task #$TASK_ID"
          elif echo "$COMMITS" | grep -q '^docs'; then
              TITLE="Documentação: $DESCRICAO_BRANCH - Task #$TASK_ID"
          elif echo "$COMMITS" | grep -q '^mant'; then
              TITLE="Manutenção: $DESCRICAO_BRANCH - Task #$TASK_ID"
          elif echo "$COMMITS" | grep -q '^oper'; then
              TITLE="Operacional: $DESCRICAO_BRANCH - Task #$TASK_ID"
          else
              TITLE="Atualização: $DESCRICAO_BRANCH - Task #$TASK_ID"
          fi

          # Create PR body with commits list
          DESCRIPTION="## Commits\n$COMMITS"

          echo "pr_title=$TITLE" >> $GITHUB_ENV
          echo "pr_body=$DESCRIPTION" >> $GITHUB_ENV

      - name: Update PR with title and description
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-generated PR title and description"
          title: ${{ env.pr_title }}
          body: ${{ env.pr_body }}
          branch: ${{ env.branch_name }}
